language: node_js
node_js:
    - "4"
    - "5"
    - "6"
notifications:
    irc:
        channels:
            - "chat.freenode.net#tests-always-included"
        skip_join: true
        template:
            - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
        use_notice: true
